services:
    app:
        container_name: app
        image: arthurlehdermann/alpine-nginx-php8.1
        ports:
            - "80:80"
            - "443:443"
            - "5173:5173"
        restart: always
        environment:
            - PHP_ERROR_REPORTING=E_ALL
            - PHP_DISPLAY_ERRORS=On
            - PHP_HTML_ERRORS=On
        volumes:
            - "./:/var/www/html"
        cap_add:
            - SYS_TIME
            - SYS_NICE
        depends_on:
            - redis
            - db
    db:
        container_name: db
        image: postgres:alpine
        restart: always
        privileged: true
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_USER=agendamento"
            - "POSTGRES_PASSWORD=agendamento"
            - "POSTGRES_DB=agendamento"
        volumes:
            - "postgres_data:/var/lib/postgresql/data"
    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        privileged: true
        ports:
            - "5050:80"
        environment:
            - "PGADMIN_DEFAULT_EMAIL=agendamento@agendamento.app"
            - "PGADMIN_DEFAULT_PASSWORD=agendamento"
        volumes:
            - "./docker/.pgadmin4-servers.json:/pgadmin4/servers.json"
            - "./docker/.pgadmin4-pgpass.json:/pgadmin4/pgpass"
        depends_on:
            - db
    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - "6379:6379"
volumes:
    postgres_data:
