version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agendamento-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    networks:
      - agendamento-network

  db:
    image: postgres:14
    container_name: agendamento-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: agendamento
      POSTGRES_USER: agendamento
      POSTGRES_PASSWORD: agendamento_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - agendamento-network

  redis:
    image: redis:alpine
    container_name: agendamento-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - agendamento-network

networks:
  agendamento-network:
    driver: bridge

volumes:
  postgres-data:
